### ISSUE TITLE
Annotation of AK83 and BL225C

### ISSUE THREAD

**Issue by iwangtoknow** [hyhy8181994/Sinorhizobium-RNAseq-2020#1]
Hi,

I have read your paper on the interactions of Plant-Rhizobium with great interest.
I tried to repeat part of your analysis(Strain AK83, BL225C, Lodi as condition). 
I used NCBI annotation to build the index and got low mapping rates from Salmon in samples AK83 Lodi/blank, BL225C blank/Lodi, around 20-30%.
I noticed gene locus tags in your table are different from the NCBI version, did you re-annotate these two genomes?
How much of the mapping rate did you have for the samples I mentioned?

Best

**Comment by diCenzo-GC** [comment]
Hello,

The mapping was done by other authors on the paper, and thus you may get a better answer by contacting the corresponding authors on the paper. That said, the mapping was done using the Genbank annotations (i.e., GCA... accessions, not the GCF... accessions). From what I can tell, mapping rates were between 20-40%.

Regards,
George

**Comment by iwangtoknow** [comment]
Thanks for your answer.
Cheers

George C diCenzo ***@***.***> schrieb am So., 25. Apr. 2021,
21:57:
